### ISSUE TITLE
Uploadable pictures

### ISSUE THREAD

**Issue by reedlabotz** [acm-uiuc/liquid#167]
Have a section where people can contribute pictures.
Wish list of features:
* Mark as suitable for the public or only logged in users.
* Board to vote for best pictures (then some algorithm that would put the top N newest ones on the front page)
* Some public gallery that would use the votes and some other annotations to order the pictures.

**Comment by colegleason** [comment]
I don't want this in liquid. I would rather find some photo gallery software and deploy that.

Already thinking about this.
