### ISSUE TITLE
ACM shortlink manager

### ISSUE THREAD

**Issue by reedlabotz** [acm-uiuc/liquid#172]
It would be awesome to have a system for people to be able to add links to liquid through an interface. Currently we have all this in urls.py and its messy and not good:

    #rp redirects
    url(r'^mm/$',redirect_to, {'url': '/conference/2013/mechmania.html'}),
    url(r'^attend/$',redirect_to, {'url': '/conference/2013/register.html'}),
    url(r'^register/$',redirect_to, {'url': '/conference/2013/register.html'}),
    url(r'^helpout/$',redirect_to, {'url': '/conference/2013/volunteers.html'}),
    url(r'^schedule/$',redirect_to, {'url': '/conference/2013/schedule.html'}),
    url(r'^jobs/$',redirect_to, {'url': '/conference/2013/career_fairs.html'}),
    url(r'^jobfair/$',redirect_to, {'url': '/conference/2013/career_fairs.html'}),
    url(r'^startup/$',redirect_to, {'url': '/conference/2013/career_fairs.html'}),
    url(r'^startupfair/$',redirect_to, {'url': '/conference/2013/career_fairs.html'}),
    url(r'^mm-irc/$',redirect_to, {'url': 'http://webchat.freenode.net/?channels=%23%23mm19&uio=OT10cnVlde'}),

    #sigmusic redirects
    url(r'^chroma/$',redirect_to, {'url': '/sigmusic/chroma'}),
    url(r'^cosmos/$',redirect_to, {'url': '/sigmusic/cosmos'}),

Requirements:
1. URL manager open to all ACM members
2. Add url as a Member or as a Group.
3. Edit URLs created by you or created by a group you are an admin of. 
4. Transfer ownership to another member or to a group.
5. Approval for all new or edited urls (approvers might be top4, or top4+some, or top4+group admins
6. Logic to 302 redirect if an url is found or 404.

Optional:
Namespace for user created urls vs group created urls?
e.g.
acm.uiuc.edu/rp owned by conference group
vs 
acm.uiuc.edu/m/reedisawesome owned by member RJ Marsan

This would be a fairly easy starter project for someone.

**Comment by colegleason** [comment]
I don't want this in liquid. We can setup another tool at a special URL path to handle this.

This looks to be well supported: https://github.com/YOURLS/YOURLS

**Comment by colegleason** [comment]
And a docker container: https://registry.hub.docker.com/u/bios/docker-yourls/

**Comment by ace-n** [comment]
There's also the fact that we want to break Liquid into a bunch of separate apps. Having a central URL resolution system isn't a bad idea (especially when we split Liquid up), but I'm not sure if we need a separate ACM shortlink manager (since "acm.illinois.edu" is already fairly long, and many other services e.g. bitly and goo.gl exist for this purpose) unless we need URLs unaffiliated with such a service.

**Comment by CJS7070** [comment]
Further, we'd need someone to take responsibility of it (since I don't think Admin should be required to maintain this as it's not a core service and we've been handling vanity URLs through our web server (since there are really only a handful of business use cases for them right now).

**Comment by colegleason** [comment]
We already have enough linkrot. We can build this out once we learn to fix that.
