### ISSUE TITLE
Carousel Broken in Chrome/Firefox

### ISSUE THREAD

**Issue by mvd7793** [acm-uiuc/liquid#173]
The carousel on the homepage is broken for me in Chrome/Firefox. It won't change images, and the buttons flicker when I move my mouse over them. (I can't click them). It works in Safari.

**Comment by colegleason** [comment]
@achalv can you still look into this?

**Comment by achalv** [comment]
Sure thing. Can ya give me a day's time? I'm getting on a flight back to the US in a little bit.

**Comment by colegleason** [comment]
Yeah, no problem.

**Comment by achalv** [comment]
Found and fixed the bug, issuing a PR.
