### ISSUE TITLE
(Suggestion) Add link to Goodwin and Main bus stop schedule to kiosk

### ISSUE THREAD

**Issue by ace-n** [acm-uiuc/liquid#197]
What do you guys think about this idea? (I personally think it would be really useful.)

**Comment by colegleason** [comment]
Sure. Can you handle that?

**Comment by CJS7070** [comment]
FWIW - we don't have any web kiosk instances right now. I don't think we're likely to have any of these set up except for special events -- and even then, it's not looking like we'll have any.

**Comment by colegleason** [comment]
Oh, did we kill the one in the front room?

**Comment by ace-n** [comment]
Yeah - it's a workstation now IIRC.

Also: If/when we're sure we won't use this page any more, can we remove it?
It's that not hard to recreate, and we don't need more dust gathering cruft
in Liquid.

**Comment by ace-n** [comment]
(Workstation = "login with your username and password")

**Comment by colegleason** [comment]
Ah right, well we can add bus stop times to the display board.

**Comment by CJS7070** [comment]
It's an ACM restricted workstation now. It didn't really make sense to have an open web kiosk on a desk that's intended for members to sit at (which is its current configuration).

I really don't think we'll use the kiosk feature again.
